version: "3.9"
services:
  postgres-db:
    image: postgres:14.5
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
#  candy-service:
#    build:
#      context: candy-service
#      dockerfile: Dockerfile
#      target: development-build
#      args:
#        - registry=$registry
#        - http_proxy=$HTTP_PROXY
#        - https_proxy=$HTTPS_PROXY
#    hostname: candy-service
#    ports:
#      - "3500:3500"
#    depends_on:
#      postgres-db:
#        condition: service_healthy
  # candy-app:
  #   build:
  #     context: candy-app
  #     dockerfile: Dockerfile
  #     target: development-build
  #     args:
  #       - registry=$registry
  #       - http_proxy=$HTTP_PROXY
  #       - https_proxy=$HTTPS_PROXY
  #   hostname: candy-app
  #   ports:
  #     - "3000:3100"
  # candy-host:
  #   build:
  #     context: candy-service
  #     dockerfile: Dockerfile
  #     target: development-build
  #     args:
  #       - registry=$registry
  #       - http_proxy=$HTTP_PROXY
  #       - https_proxy=$HTTPS_PROXY
  #   hostname: candy-host
  #   ports:
  #     - "3000:3000"

volumes:
  postgres:
